basePath: /
definitions:
  schemas.InputMessage:
    properties:
      message:
        type: string
    required:
    - message
    type: object
externalDocs:
  description: OpenAPI
  url: https://swagger.io/resources/open-api/
host: localhost:8080
info:
  contact:
    email: khiemledev@gmail.com
    name: Khiem Le
    url: https://khiemle.dev
  description: This is the Swagger documentation for golang template.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Golang Template Swagger Documentation
  version: 0.0.1
paths:
  /chat:
    post:
      consumes:
      - application/json
      description: Chat message
      parameters:
      - description: Chat message
        in: body
        name: RequestBody
        required: true
        schema:
          $ref: '#/definitions/schemas.InputMessage'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Chat message
      tags:
      - Chat
swagger: "2.0"
